### ISSUE TITLE
LGTMの文字がキャラクターの顔に被らないようにする工夫

### ISSUE THREAD

**Issue by yoshikyoto** [yoshikyoto/lgtmoon#9]
顔認識とか使えたら面白い

**Comment by lethe2211** [comment]
I think it's OK for the time being that it provides a feature to move "LGTM" to anywhere.

**Comment by yoshikyoto** [comment]
LGTM

**Comment by yoshikyoto** [comment]
![LGTM](https://pbs.twimg.com/media/CbPl0bVUYAAhz9A.jpg)

**Comment by yoshikyoto** [comment]
![img_7204](https://cloud.githubusercontent.com/assets/5354310/20920387/1f25b204-bbe3-11e6-9b75-66d9f5fc0ddf.GIF)
